/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Model.dao.CampeonatoDAO;
import Models.Campeonato;
import java.time.OffsetDateTime;

/**
 *
 * @author cmate
 */
public class FrameCadastroCampeonato extends javax.swing.JFrame {

    /**
     * Creates new form FrameCadastroCampeonato
     */
    public FrameCadastroCampeonato() {
        initComponents();
        
        tfIdUsuario.setEditable(false);
        tfIdUsuario.setText(String.valueOf(FrameLogin.iduser));
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btCadastrarCamp = new javax.swing.JButton();
        tfNomeCamp = new javax.swing.JTextField();
        tfIdUsuario = new javax.swing.JTextField();
        Fundo = new javax.swing.JLabel();
        telainteira = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btCadastrarCamp.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btCadastrarCamp.setText("CADASTRAR");
        btCadastrarCamp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCadastrarCampActionPerformed(evt);
            }
        });
        getContentPane().add(btCadastrarCamp, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 420, 120, 40));

        tfNomeCamp.setFont(new java.awt.Font("Dialog", 1, 20)); // NOI18N
        tfNomeCamp.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(tfNomeCamp, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 230, 280, 50));

        tfIdUsuario.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        tfIdUsuario.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tfIdUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfIdUsuarioActionPerformed(evt);
            }
        });
        getContentPane().add(tfIdUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 340, 180, 50));

        Fundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/FundoCadastrarCamp.png"))); // NOI18N
        getContentPane().add(Fundo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
        getContentPane().add(telainteira, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 53, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void tfIdUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfIdUsuarioActionPerformed
        
    }//GEN-LAST:event_tfIdUsuarioActionPerformed

    private void btCadastrarCampActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCadastrarCampActionPerformed
        cadastrarcamp();
        
    }//GEN-LAST:event_btCadastrarCampActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameCadastroCampeonato.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrameCadastroCampeonato.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrameCadastroCampeonato.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameCadastroCampeonato.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrameCadastroCampeonato().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Fundo;
    private javax.swing.JButton btCadastrarCamp;
    private javax.swing.JLabel telainteira;
    private javax.swing.JTextField tfIdUsuario;
    private javax.swing.JTextField tfNomeCamp;
    // End of variables declaration//GEN-END:variables
private void cadastrarcamp(){
    CampeonatoDAO dao = new CampeonatoDAO();
        Campeonato campeonato = new Campeonato();
        
        
        String nomecamp = tfNomeCamp.getText();
        campeonato.setNome(nomecamp);
        campeonato.setUsuarioId(FrameLogin.iduser);
        campeonato.setData(OffsetDateTime.now());
        
        dao.create(campeonato);
    
        FrameCampeonatos tela = new FrameCampeonatos();
        tela.setVisible(true);
        this.dispose();
}

}
