/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Model.dao.TimeDAO;
import Models.Time;
import javax.swing.JOptionPane;

/**
 *
 * @author cmate
 */
public class FrameCadastrarTime extends javax.swing.JFrame {

    /**
     * Creates new form FrameCadastrarTime
     */
    public FrameCadastrarTime() {
        initComponents();

        tfCampeonatoID.setEditable(false);
        tfCampeonatoID.setText(String.valueOf(FrameVisualizarCampeonato.idcamp));

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        tfCampeonatoID = new javax.swing.JTextField();
        tfNome = new javax.swing.JTextField();
        fundo = new javax.swing.JLabel();
        telaCheia = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setText("CADASTRAR TIME");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 420, 140, 40));

        tfCampeonatoID.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        tfCampeonatoID.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(tfCampeonatoID, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 350, 190, 50));
        getContentPane().add(tfNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 230, 170, 50));

        fundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/CADASTRAR TIME.png"))); // NOI18N
        getContentPane().add(fundo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
        getContentPane().add(telaCheia, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 550, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        cadastrartime();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameCadastrarTime.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrameCadastrarTime.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrameCadastrarTime.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameCadastrarTime.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrameCadastrarTime().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel fundo;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel telaCheia;
    private javax.swing.JTextField tfCampeonatoID;
    private javax.swing.JTextField tfNome;
    // End of variables declaration//GEN-END:variables

    private void cadastrartime() {

        if (tfNome.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "ERRO! CAMPO NOME ESTÁ VAZI0");
        } else {

            TimeDAO dao = new TimeDAO();
            Time time = new Time();

            String nometime = tfNome.getText();
            time.setNome(nometime);
            time.setCampeonatoId(FrameVisualizarCampeonato.idcamp);

            dao.create(time);

            FrameMenuPrincipal tela = new FrameMenuPrincipal();
            tela.setVisible(true);
            this.dispose();
        }

    }
}