/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;






/**
 *
 * @author cmate
 */
public class FrameCadastrarPartida extends javax.swing.JFrame {

    
    /**
     * Creates new form FrameCadastrarPartida
     */
    public FrameCadastrarPartida() {
        initComponents();
      
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel5 = new javax.swing.JLabel();
        tfResultadoMapa1EquipeA = new javax.swing.JTextField();
        tfResultadoMapa3EquipeA = new javax.swing.JTextField();
        tfResultadoMapa2EquipeA = new javax.swing.JTextField();
        labelEquipeAmapa2 = new javax.swing.JLabel();
        labelEquipeAmapa3 = new javax.swing.JLabel();
        labelEquipeAmapa1 = new javax.swing.JLabel();
        labelEquipeBmapa1 = new javax.swing.JLabel();
        tfResultadoMapa1EquipeB = new javax.swing.JTextField();
        tfResultadoMapa2EquipeB = new javax.swing.JTextField();
        tfResultadoMapa3EquipeB = new javax.swing.JTextField();
        labelEquipeBmapa3 = new javax.swing.JLabel();
        labelEquipeBmapa2 = new javax.swing.JLabel();
        labelPTcadastradas = new javax.swing.JLabel();
        jRadioMelhorde1 = new javax.swing.JRadioButton();
        jComboEquipeB = new javax.swing.JComboBox<>();
        jRadioMelhorde3 = new javax.swing.JRadioButton();
        jComboEquipeA = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jComboMapas1 = new javax.swing.JComboBox<>();
        jComboMapas2 = new javax.swing.JComboBox<>();
        jComboMapas3 = new javax.swing.JComboBox<>();
        btCadastrarPartida = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        labelIconeVoltar = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setText("Resultados:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 260, -1, -1));

        tfResultadoMapa1EquipeA.setToolTipText("");
        tfResultadoMapa1EquipeA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfResultadoMapa1EquipeAActionPerformed(evt);
            }
        });
        getContentPane().add(tfResultadoMapa1EquipeA, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 300, 50, 30));

        tfResultadoMapa3EquipeA.setToolTipText("");
        tfResultadoMapa3EquipeA.setEnabled(false);
        tfResultadoMapa3EquipeA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfResultadoMapa3EquipeAActionPerformed(evt);
            }
        });
        getContentPane().add(tfResultadoMapa3EquipeA, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 400, 50, 30));

        tfResultadoMapa2EquipeA.setToolTipText("");
        tfResultadoMapa2EquipeA.setEnabled(false);
        tfResultadoMapa2EquipeA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfResultadoMapa2EquipeAActionPerformed(evt);
            }
        });
        getContentPane().add(tfResultadoMapa2EquipeA, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 350, 50, 30));

        labelEquipeAmapa2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        labelEquipeAmapa2.setText("Equipe A");
        getContentPane().add(labelEquipeAmapa2, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 360, -1, -1));

        labelEquipeAmapa3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        labelEquipeAmapa3.setText("Equipe A");
        getContentPane().add(labelEquipeAmapa3, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 410, -1, -1));

        labelEquipeAmapa1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        labelEquipeAmapa1.setText("Equipe A");
        getContentPane().add(labelEquipeAmapa1, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 310, -1, 20));

        labelEquipeBmapa1.setText("Equipe B");
        getContentPane().add(labelEquipeBmapa1, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 310, -1, -1));

        tfResultadoMapa1EquipeB.setToolTipText("");
        tfResultadoMapa1EquipeB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfResultadoMapa1EquipeBActionPerformed(evt);
            }
        });
        getContentPane().add(tfResultadoMapa1EquipeB, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 300, 50, 30));

        tfResultadoMapa2EquipeB.setToolTipText("");
        tfResultadoMapa2EquipeB.setEnabled(false);
        tfResultadoMapa2EquipeB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfResultadoMapa2EquipeBActionPerformed(evt);
            }
        });
        getContentPane().add(tfResultadoMapa2EquipeB, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 350, 50, 30));

        tfResultadoMapa3EquipeB.setToolTipText("");
        tfResultadoMapa3EquipeB.setEnabled(false);
        tfResultadoMapa3EquipeB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfResultadoMapa3EquipeBActionPerformed(evt);
            }
        });
        getContentPane().add(tfResultadoMapa3EquipeB, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 400, 50, 30));

        labelEquipeBmapa3.setText("Equipe B");
        getContentPane().add(labelEquipeBmapa3, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 410, -1, -1));

        labelEquipeBmapa2.setText("Equipe B");
        getContentPane().add(labelEquipeBmapa2, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 360, -1, -1));

        labelPTcadastradas.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        labelPTcadastradas.setText("0 Partidas Cadastradas");
        getContentPane().add(labelPTcadastradas, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 510, -1, -1));

        buttonGroup1.add(jRadioMelhorde1);
        jRadioMelhorde1.setText("1");
        jRadioMelhorde1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jRadioMelhorde1MouseClicked(evt);
            }
        });
        jRadioMelhorde1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioMelhorde1ActionPerformed(evt);
            }
        });
        getContentPane().add(jRadioMelhorde1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 280, -1, -1));

        jComboEquipeB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Astralis", "BNE", "BIG", "Imperial" }));
        jComboEquipeB.setBorder(javax.swing.BorderFactory.createTitledBorder("Equipe B"));
        jComboEquipeB.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboEquipeBItemStateChanged(evt);
            }
        });
        jComboEquipeB.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentHidden(java.awt.event.ComponentEvent evt) {
                jComboEquipeBComponentHidden(evt);
            }
        });
        jComboEquipeB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboEquipeBActionPerformed(evt);
            }
        });
        getContentPane().add(jComboEquipeB, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 170, 140, 60));

        buttonGroup1.add(jRadioMelhorde3);
        jRadioMelhorde3.setText("3");
        jRadioMelhorde3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jRadioMelhorde3MouseClicked(evt);
            }
        });
        jRadioMelhorde3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioMelhorde3ActionPerformed(evt);
            }
        });
        getContentPane().add(jRadioMelhorde3, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 280, -1, -1));

        jComboEquipeA.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Astralis", "BNE", "BIG", "Imperial" }));
        jComboEquipeA.setBorder(javax.swing.BorderFactory.createTitledBorder("Equipe A"));
        jComboEquipeA.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboEquipeAItemStateChanged(evt);
            }
        });
        jComboEquipeA.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
                jComboEquipeACaretPositionChanged(evt);
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
            }
        });
        getContentPane().add(jComboEquipeA, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 170, 140, 60));

        jLabel1.setText("Melhor de:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 260, -1, -1));

        jComboMapas1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Mirage", "Dust2", "Inferno", "Overpass" }));
        jComboMapas1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jComboMapas1.setOpaque(true);
        jComboMapas1.setPreferredSize(new java.awt.Dimension(85, 43));
        jComboMapas1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboMapas1ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboMapas1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 310, -1, 30));

        jComboMapas2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Mirage", "Dust2", "Inferno", "Overpass" }));
        jComboMapas2.setEnabled(false);
        jComboMapas2.setPreferredSize(new java.awt.Dimension(85, 43));
        getContentPane().add(jComboMapas2, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 350, -1, -1));

        jComboMapas3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Mirage", "Dust2", "Inferno", "Overpass" }));
        jComboMapas3.setEnabled(false);
        jComboMapas3.setPreferredSize(new java.awt.Dimension(85, 43));
        getContentPane().add(jComboMapas3, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 400, -1, -1));

        btCadastrarPartida.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btCadastrarPartida.setText("Cadastrar Partida");
        btCadastrarPartida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCadastrarPartidaActionPerformed(evt);
            }
        });
        getContentPane().add(btCadastrarPartida, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 470, 170, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("MATCH INFO");
        jLabel2.setMaximumSize(new java.awt.Dimension(500, 250));
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 1000, 50));

        labelIconeVoltar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelIconeVoltarMouseClicked(evt);
            }
        });
        getContentPane().add(labelIconeVoltar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, -1));
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 540, 20, 10));

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("x");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 410, 30, 10));

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("x");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 310, 30, 10));

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("x");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 360, 30, 10));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void tfResultadoMapa1EquipeAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfResultadoMapa1EquipeAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfResultadoMapa1EquipeAActionPerformed

    private void tfResultadoMapa3EquipeAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfResultadoMapa3EquipeAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfResultadoMapa3EquipeAActionPerformed

    private void tfResultadoMapa2EquipeAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfResultadoMapa2EquipeAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfResultadoMapa2EquipeAActionPerformed

    private void tfResultadoMapa1EquipeBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfResultadoMapa1EquipeBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfResultadoMapa1EquipeBActionPerformed

    private void tfResultadoMapa2EquipeBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfResultadoMapa2EquipeBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfResultadoMapa2EquipeBActionPerformed

    private void tfResultadoMapa3EquipeBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfResultadoMapa3EquipeBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfResultadoMapa3EquipeBActionPerformed

    private void jRadioMelhorde1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jRadioMelhorde1MouseClicked

    }//GEN-LAST:event_jRadioMelhorde1MouseClicked

    private void jRadioMelhorde1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioMelhorde1ActionPerformed
        jComboMapas2.setEnabled(false);
        jComboMapas3.setEnabled(false);
        tfResultadoMapa2EquipeA.setEnabled(false);
        tfResultadoMapa3EquipeA.setEnabled(false);
        tfResultadoMapa2EquipeB.setEnabled(false);
        tfResultadoMapa3EquipeB.setEnabled(false);

    }//GEN-LAST:event_jRadioMelhorde1ActionPerformed

    private void jComboEquipeBItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboEquipeBItemStateChanged

        labelEquipeBmapa1.setText((String) jComboEquipeB.getSelectedItem());
        labelEquipeBmapa2.setText((String) jComboEquipeB.getSelectedItem());
        labelEquipeBmapa3.setText((String) jComboEquipeB.getSelectedItem());
    }//GEN-LAST:event_jComboEquipeBItemStateChanged

    private void jComboEquipeBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboEquipeBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboEquipeBActionPerformed

    private void jRadioMelhorde3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jRadioMelhorde3MouseClicked

    }//GEN-LAST:event_jRadioMelhorde3MouseClicked

    private void jRadioMelhorde3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioMelhorde3ActionPerformed
        jComboMapas2.setEnabled(true);
        jComboMapas3.setEnabled(true);
        tfResultadoMapa2EquipeA.setEnabled(true);
        tfResultadoMapa3EquipeA.setEnabled(true);
        tfResultadoMapa2EquipeB.setEnabled(true);
        tfResultadoMapa3EquipeB.setEnabled(true);
    }//GEN-LAST:event_jRadioMelhorde3ActionPerformed

    private void jComboEquipeAItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboEquipeAItemStateChanged

        labelEquipeAmapa1.setText((String) jComboEquipeA.getSelectedItem());
        labelEquipeAmapa2.setText((String) jComboEquipeA.getSelectedItem());
        labelEquipeAmapa3.setText((String) jComboEquipeA.getSelectedItem());

    }//GEN-LAST:event_jComboEquipeAItemStateChanged

    private void jComboEquipeACaretPositionChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_jComboEquipeACaretPositionChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboEquipeACaretPositionChanged

    private void jComboMapas1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboMapas1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboMapas1ActionPerformed

    private void btCadastrarPartidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCadastrarPartidaActionPerformed
      
    }//GEN-LAST:event_btCadastrarPartidaActionPerformed

    private void labelIconeVoltarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelIconeVoltarMouseClicked
        FrameMenuPrincipal menu = new FrameMenuPrincipal();
        menu.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_labelIconeVoltarMouseClicked

    private void jComboEquipeBComponentHidden(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jComboEquipeBComponentHidden
        
    }//GEN-LAST:event_jComboEquipeBComponentHidden

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameCadastrarPartida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrameCadastrarPartida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrameCadastrarPartida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameCadastrarPartida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrameCadastrarPartida().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btCadastrarPartida;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> jComboEquipeA;
    private javax.swing.JComboBox<String> jComboEquipeB;
    private javax.swing.JComboBox<String> jComboMapas1;
    private javax.swing.JComboBox<String> jComboMapas2;
    private javax.swing.JComboBox<String> jComboMapas3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JRadioButton jRadioMelhorde1;
    private javax.swing.JRadioButton jRadioMelhorde3;
    private javax.swing.JLabel labelEquipeAmapa1;
    private javax.swing.JLabel labelEquipeAmapa2;
    private javax.swing.JLabel labelEquipeAmapa3;
    private javax.swing.JLabel labelEquipeBmapa1;
    private javax.swing.JLabel labelEquipeBmapa2;
    private javax.swing.JLabel labelEquipeBmapa3;
    private javax.swing.JLabel labelIconeVoltar;
    private javax.swing.JLabel labelPTcadastradas;
    private javax.swing.JTextField tfResultadoMapa1EquipeA;
    private javax.swing.JTextField tfResultadoMapa1EquipeB;
    private javax.swing.JTextField tfResultadoMapa2EquipeA;
    private javax.swing.JTextField tfResultadoMapa2EquipeB;
    private javax.swing.JTextField tfResultadoMapa3EquipeA;
    private javax.swing.JTextField tfResultadoMapa3EquipeB;
    // End of variables declaration//GEN-END:variables
}
